package cn.mvp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.mvp.db.Todos;

import cn.mvp.db.TodosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todosDaoConfig;

    private final TodosDao todosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todosDaoConfig = daoConfigMap.get(TodosDao.class).clone();
        todosDaoConfig.initIdentityScope(type);

        todosDao = new TodosDao(todosDaoConfig, this);

        registerDao(Todos.class, todosDao);
    }
    
    public void clear() {
        todosDaoConfig.clearIdentityScope();
    }

    public TodosDao getTodosDao() {
        return todosDao;
    }

}
